### ISSUE TITLE
Please add mxnet

### ISSUE THREAD

**Issue by sazari** [jrowen/dcaret#1]
Could you add mxnet to the container, please?

**Comment by jrowen** [comment]
Do you want to submit a pull request?  If not, I'm happy to make the update.

**Comment by sazari** [comment]
Jonathan,

Please make the update.

Regards,
Sardar.

**Comment by jrowen** [comment]
The container has been updated.  There's an issue with the Travis build, but the Docker Hub build was successful.  I'll try to fix the Travis build shortly.
